name: System Info Reporter

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  report-system:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    # - name: Run system info script
    #   run: |
    #     python system_info.py
    - name: Run Python script
      run: |
        echo 'import platform; import sys; print("="*50); print(f"操作系统: {platform.system()}"); print(f" 
架构信息: {platform.machine()}"); print(f"平台详情: {platform.platform()}"); print(f"Python 版本: {sys.version}"); print("="*50)' >>t.py
        python t.py
